pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        sh 'dotnet build'
      }
    }

    stage('Unit Tests') {
      steps {
        sh 'dotnet test --logger:xunit'
      }

      post {
        always {
          xunit(tools: [xUnitDotNet(pattern: '**/TestResults/*.xml')])
        }
      }
    }

    stage('Staging') {
      steps {
        sh "sudo dotnet publish HelloMvc --configuration Debug --output /opt/HelloMvcStaging"
      }
    }

    stage('Deploy') {
      agent {
        label 'master'
      }

      when {
        beforeInput true
        beforeAgent true
        tag 'release-*'
      }

      input {
        message "Deploy ${env.TAG_NAME} to production servers?"
      }

      steps {
        sh "sudo dotnet publish HelloMvc --configuration Release --output /opt/HelloMvcProduction"
      }
    }
  }

}
